### ISSUE TITLE
Error: Cannot find module '@actions/core'

### ISSUE THREAD

**Issue by jsodeman** [sand4rt/ftp-deployer#1]
```
jobs:
  build:
    name: Production
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12.18.3'
           
    # other stuff
    
    - name: Deploy
      uses: sand4rt/ftp-deployer@v0.1
      with:
        host: ************
        username: ************
        password: ************
        local_folder: ************
        cleanup: true
```

```
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module '@actions/core'
Require stack:
- D:\a\_actions\sand4rt\ftp-deployer\v0.1\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (D:\a\_actions\sand4rt\ftp-deployer\v0.1\index.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'D:\\a\\_actions\\sand4rt\\ftp-deployer\\v0.1\\index.js' ]
}
```

**Comment by sand4rt** [comment]
You are not using the latest version of ftp-deployer. Use v0.9 like:

```
- name: Deploy
   uses: sand4rt/ftp-deployer@v0.9
   with:
     host: ************
     username: ************
     password: ************
     local_folder: ************
     cleanup: true
```
