### ISSUE TITLE
(node:1715) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

### ISSUE THREAD

**Issue by BaseMax** [sand4rt/ftp-deployer#18]
```
    - name: FTP Deployer
      uses: sand4rt/ftp-deployer@v1.5
      with:
        sftp: true
        host: ${{ secrets.SERVER_HOST }}
        port: ${{ secrets.SERVER_PORT }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER _PASSWORD }}
        remote_folder: '/home/maxbase/public_html/test/'
        local_folder: 'build/'
        cleanup: false
        include: '[ "*", "**/*" ]'
        exclude: '["node_modules/**", ".github/**", ".git/**", "*.env"]'
```
