### ISSUE TITLE
Actions not works after upgrade from 1.4 to 1.5

### ISSUE THREAD

**Issue by BaseMax** [sand4rt/ftp-deployer#19]
The following job works:
```
      
    - name: FTP Deployer
      uses: sand4rt/ftp-deployer@v1.4
      with:
        sftp: true
        host: asrez.com
        port: 22
        username: username
        password: ${{ secrets.FTP_PASSWORD }}
        remote_folder: '/home/maxbase/public_html/test-react/'
        local_folder: 'build/'
        cleanup: false
        include: '[ "*", "**/*" ]'
        exclude: '["node_modules/**", "_secret.php", ".github/**", ".git/**", "*.env"]'
        pasive: true
```

But when you change version from 1.4 to 1.5, It not works (Also we must remove pasive):
```
      
    - name: FTP Deployer
      uses: sand4rt/ftp-deployer@v1.4
      with:
        sftp: true
        host: asrez.com
        port: 22
        username: username
        password: ${{ secrets.FTP_PASSWORD }}
        remote_folder: '/home/maxbase/public_html/test-react/'
        local_folder: 'build/'
        cleanup: false
        include: '[ "*", "**/*" ]'
        exclude: '["node_modules/**", "_secret.php", ".github/**", ".git/**", "*.env"]'
```
