### ISSUE TITLE
A warning for version 1.4

### ISSUE THREAD

**Issue by BaseMax** [sand4rt/ftp-deployer#20]
```
on: [push]

jobs:
  mirror_with_sftp:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: FTP Deployer
        uses: sand4rt/ftp-deployer@v1.4
        with:
          sftp: true
          host: ${{ secrets.SERVER_HOST }}
          port: 22
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          remote_folder: ${{ secrets.SERVER_PATH }}
          local_folder: '.'
          cleanup: false
          include: '[ "*", "**/*" ]'
          exclude: '["src/core/db.php", "node_modules/**", "_secret.php", ".github/**", ".git/**", "*.env"]'
          pasive: true
```

**Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout@v2, sand4rt/ftp-deployer@v1.4**

![image](https://user-images.githubusercontent.com/2658040/202362965-b79a29d1-9b05-4e1e-a34f-0e1d1aa3fe8e.png)
