### ISSUE TITLE
confusing action param

### ISSUE THREAD

**Issue by StageGuard** [sand4rt/ftp-deployer#7]
It says in readme: 
```yaml
    include: '' # optional, e.g.
      # - dist
    exclude: '' # optional
      # - node_modules/**
      # - node_modules/**/.*
      # - .git/**
      # - *.env
```
seems that I need to provide a yaml raw list, but actually: 
[index.js](https://github.com/sand4rt/ftp-deployer/blob/master/index.js#L16)
```javascript
include: JSON.parse(core.getInput('include')) || ['*', '**/*'], // this would upload everything except dot files
exclude: JSON.parse(core.getInput('exclude')) || ['node_modules/**', 'node_modules/**/.*', '.git/**'], // e.g. exclude sourcemaps, and ALL files in node_modules (including dot files)
```
It parses a json array string.
I think no one will understand how to deploy this action until he or she read index.js
